Repository 4paradigm/HybridSE, pull requests merged in 2021-06, with the labels that each got.

#115 feat: support subquery table and subquery expression
  cases/plan/error_unsupport_sql.yaml
  cases/plan/join_query.yaml
  cases/plan/simple_query.yaml
  cases/plan/sub_query.yaml
  cases/plan/union_query.yaml
  cases/plan/where_query.yaml
  cases/plan/window_query.yaml
  include/node/node_manager.h
  include/node/sql_node.h
  src/node/expr_node.cc
  src/node/node_manager.cc
  src/node/sql_node.cc
  src/parser/sql_parser.y
  src/planv2/CMakeLists.txt
  src/planv2/ast_node_converter.cc
  src/planv2/ast_node_converter.h
  src/planv2/ast_node_converter_test.cc
  src/planv2/planner_v2.cc
  src/planv2/planner_v2_test.cc
  tools/init_env.profile.sh
  tools/install_thirdparty_mac.sh
Labels: module:parser, module:plan

#127 fix: java lib version
  java/pom.xml
Labels: bug, deploy

#117 feat: support setting jsdk library file path for jit manager
  java/hybridse-sdk/src/main/java/com/_4paradigm/hybridse/HybridSeLibrary.java
  java/hybridse-sdk/src/main/java/com/_4paradigm/hybridse/sdk/JitManager.java
Labels: enhancement

#119 feat: support encode and decode string for Spark UnsafeRow format
  include/codec/list_iterator_codec.h
  include/codec/type_codec.h
  src/codec/fe_row_codec.cc
  src/codec/fe_row_codec_test.cc
  src/codec/type_codec.cc
  src/codegen/buf_ir_builder.cc
  src/codegen/buf_ir_builder_test.cc
Labels: enhancement

#128 feat: 105 create procedure
  cases/plan/create.yaml
  include/case/sql_case.h
  include/node/node_manager.h
  include/node/sql_node.h
  src/case/sql_case.cc
  src/node/node_manager.cc
  src/node/sql_node.cc
  src/parser/sql_parser_test.cc
  src/plan/planner_test.cc
  src/planv2/ast_node_converter.cc
  src/planv2/ast_node_converter.h
  src/planv2/ast_node_converter_test.cc
  src/planv2/planner_v2_test.cc
Labels: module:parser
