Repository 4paradigm/HybridSE, pull requests merged in 2021-07, with the labels that each got.

#145 feat: support insert statement with placeholder
  CMakeLists.txt
  cases/insert/simple_insert.yaml
  cases/integration/v1/test_create.yaml
  cases/integration/v1/test_insert.yaml
  cases/plan/cmd.yaml
  cases/plan/create.yaml
  cases/plan/error_unsupport_sql.yaml
  cases/plan/insert.yaml
  examples/toydb/src/sdk/dbms_sdk_test.cc
  examples/toydb/src/sdk/tablet_sdk.cc
  include/case/sql_case.h
  include/node/node_enum.h
  include/node/node_manager.h
  include/node/plan_node.h
  include/node/sql_node.h
  src/case/sql_case.cc
  src/node/node_manager.cc
  src/node/plan_node.cc
  src/node/plan_node_test.cc
  src/node/sql_node.cc
  src/node/sql_node_test.cc
  src/plan/planner.cc
  src/plan/planner.h
  src/planv2/ast_node_converter.cc
  src/planv2/ast_node_converter.h
  src/planv2/ast_node_converter_test.cc
  src/planv2/planner_v2_test.cc
  src/testing/test_base.cc
Labels: WIP

#149 ci: support codeql
  .github/workflows/codeql-analysis.yml
Labels: workflow

#152 build: static link glog & gflags on mac
  .github/workflows/hybridse-ci.yml
  CMakeLists.txt
  tools/init_env.profile.sh
  tools/install_thirdparty_mac.sh
Labels: bug, workflow

#154 build: update version to 0.1.5
  CMakeLists.txt
  java/hybridse-native/pom.xml
  java/hybridse-proto/pom.xml
  java/hybridse-sdk/pom.xml
  java/pom.xml
Labels: build

#156 fix: #147, test report contains GoogleTestVerification
  examples/toydb/src/sdk/dbms_sdk_test.cc
  examples/toydb/src/sdk/result_set_impl_test.cc
  examples/toydb/src/sdk/tablet_sdk_test.cc
  examples/toydb/src/testing/toydb_engine_test.cc
  src/codec/schema_codec_test.cc
  src/passes/physical/batch_request_optimize_test.cc
  src/planv2/ast_node_converter_test.cc
  src/planv2/planner_v2_test.cc
  src/testing/engine_test_base.cc
  src/testing/engine_test_base.h
  src/vm/logical_graph_test.cc
  src/vm/runner_test.cc
  src/vm/schemas_context_test.cc
  src/vm/sql_compiler_test.cc
  src/vm/transform_request_mode_test.cc
  src/vm/transform_test.cc
Labels: bug

#164 fix: change lead function to lag function
  CHANGELOG.md
  CMakeLists.txt
  cases/integration/fz_ddl/test_luoji.yaml
  cases/integration/fz_ddl/test_myhug.yaml
  cases/integration/spark/test_ads.yaml
  cases/integration/spark/test_news.yaml
  cases/integration/v1/function/test_udaf_function.yaml
  cases/integration/v1/test_feature_zero_function.yaml
  cases/integration/v1/test_fz_sql.yaml
  cases/integration/v1/window/test_window_row.yaml
  cases/integration/v1/window/test_window_union.yaml
  cases/query/fz_sql.yaml
  java/hybridse-native/pom.xml
  java/hybridse-proto/pom.xml
  java/hybridse-sdk/pom.xml
  java/pom.xml
  src/passes/expression/merge_aggregations_test.cc
  src/passes/expression/window_iter_analysis_test.cc
  src/passes/lambdafy_projects_test.cc
  src/planv2/planner_v2_test.cc
  src/udf/default_defs/window_functions_def.cc
Labels: bug

#160 feat: orderby node rfc
  cases/integration/cluster/window_and_lastjoin.yaml
  cases/integration/v1/test_index_optimized.yaml
  cases/integration/v1/window/test_window_row_range.yaml
  cases/plan/order_query.yaml
  cases/query/window_with_union_query.yaml
  include/node/node_enum.h
  include/node/node_manager.h
  include/node/plan_node.h
  include/node/sql_node.h
  include/vm/physical_op.h
  src/node/expr_node.cc
  src/node/node_manager.cc
  src/node/plan_node.cc
  src/node/plan_node_test.cc
  src/node/sql_node.cc
  src/node/sql_node_test.cc
  src/passes/physical/group_and_sort_optimized.cc
  src/passes/physical/left_join_optimized.cc
  src/planv2/ast_node_converter.cc
  src/planv2/planner_v2_test.cc
  src/vm/physical_op.cc
  src/vm/physical_plan_context.cc
  src/vm/physical_plan_context.h
  src/vm/transform.cc
  src/vm/transform_request_mode_test.cc
  src/vm/transform_test.cc
Labels: refactor

#177 build: using thirdparty-mac 0.1.4 and fix cmake
  .github/workflows/hybridse-ci.yml
  CMakeLists.txt
  tools/setup_thirdparty.sh
Labels: build

#182 feat: add parameter expr
  cases/plan/insert.yaml
  cases/plan/where_query.yaml
  include/node/node_enum.h
  include/node/node_manager.h
  include/node/sql_node.h
  src/node/expr_node.cc
  src/node/node_manager.cc
  src/node/sql_node.cc
  src/node/sql_node_test.cc
  src/passes/lambdafy_projects.cc
  src/planv2/ast_node_converter.cc
Labels: sql
